version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/app
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: "development"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
